kafka.bootstrap.servers=kafka-broker.example.com:9094
kafka.group.id=my-consumer-group
kafka.topic=my-topic
kafka.auto.offset.reset=earliest
kafka.enable.auto.commit=true
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=OAUTHBEARER
kafka.ssl.endpoint.identification.algorithm=https
kafka.ssl.ca.location=ca-kafka.pem
kafka.enable.insecure.ssl=true
