kafka.bootstrap.servers=kafka-broker.example.com:9094
kafka.topic=my-topic
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=OAUTHBEARER
kafka.ssl.endpoint.identification.algorithm=https
kafka.ssl.ca.location=
kafka.enable.insecure.ssl=true
